### ISSUE TITLE
Microarray Row do not extract any data

### ISSUE THREAD

**Issue by Patogym** [WGSExtract/WGSExtract.github.io#7] opened 2021-07-01 11:25 UTC
Hello,

I have a CRAM file from Nebula, converted to BAM with WGSE.
I want to extract Data.
It is working with Mitochondrial DNA option and Y Chromosome option, but not with Microarray Test option.
The extraction is starting, working normally, no error, and at the end, no files in output folder.
During extraction, there are 2 files in Temp folder (ButtonCombinedKit.sh and CombKit_called.vcf.gz, this one is going bigger during extraction).

Here is the log file attached

Regards,

[log.txt](https://github.com/WGSExtract/WGSExtract.github.io/files/6747719/log.txt)

**Comment by RandyHarr** [comment] 2021-07-01 12:56
You are the second to report this problem.  We are investigating what has crept into the win10tools zip install file to not set permissions of the tmp directory correctly.  The installer tries to override but is not able to from BASH.  The issue is the sort command is not getting access to the win10tools/tmp directory.  Possibly the temp in the WGS Extract installation as well. 

I will look into this more and figure out how to resolve permanently and for you in the near term.  Not all installations seem to have this issue so we have not characterized why it happens infrequently yet.

**Comment by teepean** [comment] 2021-07-01 20:54
The issue is caused by this line in Upgrade_UbuntuLinux.sh

`  # Final cleanup that is not handled by initial Cygin64 install via cmd.exe
  chmod 777 win10tools/tmp`

**Comment by RandyHarr** [comment] 2021-07-02 01:14
Wait, what? The line is basically ineffective that I can tell. How is it the cause of the issue?

**Comment by teepean** [comment] 2021-07-02 04:16
I managed to recreate the issue. If a directory is outside Cygwin's own tree then chmod will screw up the security permissions. The fix on Cygwin is to add option noacl to /etc/fstab but that is not possible in WGSExtract's case.

https://cygwin.com/cygwin-ug-net/using-filemodes.html

https://stackoverflow.com/questions/48550517/creating-folders-in-cygwin-results-in-incorrectly-ordered-permissions-failure-t

**Comment by RandyHarr** [comment] 2021-07-02 13:08
@Patogym I think the current answer you are looking for is. Delete the win10tools/tmp directory and recreate it. Basically, Windows ACLs on what is meant to be a Cygwin64 Linux directory are getting set to prevent the Cygwin64 sort command from accessing the directory. We are looking into how to override this during installation to prevent it from cropping up again.

**Comment by RandyHarr** [comment] 2021-07-02 14:02
Actually, buried a couple links deep is:
https://cygwin.com/cygwin-ug-net/using.html#mount-table
That is the best detailed help of what is really occurring.  Explaining Cygwin64s emulation of Unix permissions on ACL systems like NTFS. Which seems to imply we do not want to use the NOACL option on NTFS systems (which most will likely have).

My guess is an intermediate win10tools release .zip was used and upgraded from.  And that intermediate one used Win10 Compress instead of 7zip to create the .zip.  Win10 compress stores ACL info in the .zip ; which is non-standard.  Just as the release .zip's are now made in MacOS with BOM to help get their hidden bits set right for Apple systems, we have to normally use 7zip to create the win10tools releases from getting ACLs transferred.  I also had to tune the unzip command in Win10 installs to avoid ACL corruption as well.  Forcing me to include 7zip in the Win10 release and use it.

I would still like to figure out a way to assure this does not crop up in the future. My guess at this point is to not include /tmp in the Win10tools release and instead create it as part of the install process.  But can we reliably do that in Cygwin64 BASH or do we have to do it in CMD batch? Is creating it more reliable to get the ACLs correct than transferring it in the .zip with 7Zip the way we do now?

Teemu, your apparent issue with WGSE "temp" (which is outside the Cygwin64 directory) is unrelated to this.  And may be related to historical upgrades where one of the old Alpha v3 releases using Win10 Compress to make the zip led to corrupt ACLs.  I have not seen that issue for others ever but do know my development directory had some corrupted ACLs infiltrate in over time given I am constantly switching between Win10, Cygwin64, WSL and PyCharm shells in the same directory.

So in the end, is the fix to change the Win10-only  install script line: "chmod 777 tmp" (which does not do anything it ends up) to "-rmdir tmp; mkdir tmp" ?

**Comment by teepean** [comment] 2021-07-02 17:43
Hi Randy,

I think the rmdir/mkdir approach might be the best solution. Unfortunately
I can not test it until Sunday as I am not at home right now.

Regards,
Teemu

pe 2. heinäk. 2021 klo 17.02 Randy H ***@***.***> kirjoitti:

**Comment by Patogym** [comment] 2021-07-03 06:57
Hi,

It is working for me here !
Thanks

Regards,

Patrick

**Comment by RandyHarr** [comment] 2021-07-03 11:26
Will close the issue unless further testing indicates a different course of action.

**Closed by RandyHarr** 2021-07-03 11:26 UTC
