### ISSUE TITLE
Question and issue report.

### ISSUE THREAD

**Issue by RasulSrg** [WGSExtract/WGSExtract.github.io#8] opened 2021-07-06 12:38 UTC
Hello. Internet says hg38 ref. genome is better than old hs37d5, that's why i align fasta of ancient DNA against grch38 and use it with wgsextract for autosomal extraction, but when i start the process program tells me that hs37d5 bam will give more precise autosomal result. I don't understand which is really better. Please explain to me.

ISSUE - program doesn't output autosomal zip file until you flag python.exe to run with administrator rights. i am using latest build of windows home.

**Comment by RandyHarr** [comment] 2021-07-06 12:54
OK, two completely separate items.

(1) Microarray test companies deliver their results in Build 37 (/19).  Of all the build 37 models, hs37d5 has the best accuracy at calling the SNPs in the microarray files.  This mostly due to the alternate locations and decoy setup.  hs37d5 was designed by the author of the BWA aligner.  While the more modern Build 38 can cover more of the known genome, it is not how microarray results are delivered.  (And, for the most part, most medical studies of the recent past.)  Hence the recommendation of hs37d5 for microarray kit generation.  There are about 5,000 of over 600,000 SNPs that cannot translate over from build 38 to build 37. See the user manual for more information and the recommendation from the BWA aligner author on what reference genomes to use. 

Build 38 should be used for Y DNA Haplogroup work because much more of the Y chromosome is accurate there and so what the phylogenetic tree sites use. There is a dramatic difference in the haplogroup call from the different builds.  But this is mostly because the Build 37 Y annotation file has not been updated since 2017.  And way more than 1/2 the SNPs in the tree have been added since then. Build 38 should also generally be used for searching for novel variants and rare medical conditions in Autosomes.

(2) Nothing in WGS Extract requires administrative rights. Especially not Python.  During installation, some programs on Unix/Linux platforms require administrator rights because they install in system directories (as is standard for those platforms).  Please provide the capture of the command script log window showing what you believe to be a requirement for administrator rights.

I will close this as there is nothing to act on.  But you can reopen if you supply the command script log explaining your issue.

**Closed by RandyHarr** 2021-07-06 12:54 UTC

**Comment by RasulSrg** [comment] 2021-07-06 14:16
Thank you for your explanation. You can delete this thread if you want
