### ISSUE TITLE
Installing MacPorts v2.8.0 on MacOS version 14.0. ***ERROR: Do not undestand MacOS Version: 14.0 to install MacPorts software logout

### ISSUE THREAD

**Issue by sis-c** [WGSExtract/WGSExtract.github.io#21] opened 2023-10-28 06:25 UTC
Installing MacPorts v2.8.0 on MacOS version 14.0.
***ERROR: Do not undestand MacOS Version: 14.0 to install MacPorts software
logout

Intel Mac
macOS 14.0

If I install MacPorts separately will this tool skip the step?

**Comment by RandyHarr** [comment] 2023-10-28 12:39
Was wondering when this would get reported :)  I just ran into it this week while trying to push a patch update out.

You have to completely uninstall XCode and Macports.  Both can be done with the Uninstaller with WGS Extract. Neither can update between major OS releases.

The WGS Extract installer cannot pre-determine the MacPorts info to find the correct file.  So it has to wait for me to patch the code. Give me a few hours and I will put the patch here for just the MacOS installer with the 14 Sonoma update.

If you install MacPorts and XCode yourself, the installer will not try and do it again. The current version you have does not check the version numbers of those programs.  The new one about to come out will as it will do the uninstall for you; given this is a frequent and common issue with MacOS only. Am not sure why they have such an issue.  Suspect they hard link in some OS library elements from the Xcode package into MacPorts binaries.  A macports "port" command will not run when it detects the OS version has changed.  (Oddly, the "port" command is needed to properly uninstall! Clearly they have not thought this through.)

The issue is MacPorts never goes back and fills in ports for older versions from before the new OS release date. They have no "latest version" link either.  Only specific files tied to their exact version (e.g. 2.8.0), the MacOS version (e.g. 10.14 or 13), and (drum roll please), the MacOS code name (e.g. BigSur).  You can never seem to get those code names in advance anymore since they started with the new major-version numbering changes each year. (Seems Apple trademarks the name and so waits until the last possible moment to release the name so they can trademark it.)  Without the version number of MacPorts for when the new OS becomes available, it does not help to just have the code name anyway.  So I am relegated to patch the MacOS installer for each (major) MacOS update.

**Comment by RandyHarr** [comment] 2023-10-28 18:03
You can copy and paste lines from here as they have the correct spacing and such.

Using your favorite text editor, edit the file "Install_macos.command":
(1) Change line 125 to list 2.8.1 instead of its current 2.8.0
`  ver="2.8.1"     # The previous stable 2.7.2 is not available on 13.x Ventura`
(2) After line 141, add the definition for Sonoma, v14 as follows (note: keep spacing / indent and alphabetic case):
```
    14)  # Sonoma is v14.x now
          MACPORTSF="MacPorts-${ver}-14-Sonoma.pkg"     ;;
```

In the file "Uninstall_macos.command", you can comment out line 128 by inserting a hash symbol:
`    # sudo -H /opt/local/bin/port -fp uninstall installed | grep -v "Cleaning\|Deactivating\|Uninstalling"` 

Run the Uninstall_macos.command and say yes to uninstall Apple Xcode and MacPorts. Then rerun the installer and it should update MacPorts and other files, as needed.

I will close this for now but reopen if you still have issues.

**Closed by RandyHarr** 2023-10-28 18:03 UTC
